name: 'test-webdav'
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bxb100/action-upload@main
        with:
          provider: webdav
          # bug 1: not support create dir in the root webdav path, not sure is that only occurs in jianguoyun
          provider_options: |
            endpoint=https://dav.jianguoyun.com/dav
            username=${{secrets.webdav_username}}
            password=${{secrets.webdav_password}}
            root=/test-issue/
          include: |
            './**'
            '!./exclude'
            !.git
